apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - sealed-secret.yaml

nameSuffix: ''
namePrefix: imdbgraph-

commonLabels:
  app: imdbgraph

images:
  - name: docker.io/aamini/app
    newName: docker.io/aamini/imdbgraph
    newTag: latest

patches:
  - target:
      kind: HTTPRoute
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: "imdbgraph.ariaamini.com"
  - target:
      kind: Deployment
      name: app-deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value:
          - configMapRef:
              name: imdbgraph-config
          - secretRef:
              name: imdbgraph-secrets

