---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Receiver
metadata:
  name: flux-system
  namespace: flux-system
spec:
  type: generic
  secretRef:
    name: flux-webhook-token
  resources:
    - kind: GitRepository
      name: flux-system
    - kind: ImageRepository
      names:
        - imdbgraph
        - pc-tune-ups
        - dota-visualizer
        - portfolio
    - kind: ImagePolicy
      names:
        - imdbgraph
        - pc-tune-ups
        - dota-visualizer
        - portfolio
    - kind: ImageUpdateAutomation
      name: flux-system
