---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: imdbgraph-secrets
  namespace: imdbgraph
spec:
  encryptedData:
    DATABASE_URL: AgBNscv82BEzBhcxLHH+0y/eBb/V8+iGbfqXTy3vpYmZYSiV8lSvy9rY3M4TEAX6WCNQGTc73J6F+eaWX98h5zMfgWq9OszXK9Xr6s0LEbG5OQdLmfsa0uf5fd9nzrgQ9jzSjRUfmQXHWbyfxJyDuNE8SMTD6aSSddqEpS49g/fGffBq/heolgnD48Y+ISsN7EIzXTz4MBhfU8lrnHUeorkjvgK2WbkPWcuVR7NFxUi6/Bwo1z5gV0YnTNwCdvu+nKUsxcFJ+1ORCF49UJ+XbdPoRx8oogvNSkqX30UUMlp4KwzB32+SS57CQzkfmdWNauYWNQxVgjkDS9PexEwp8z+MEnn1eAAb19ec+yIOCCcGGbpD79JZ6oMk1zk8SbR0e1rI98uwcnWJBUqISZYMSw1brl9pVBQgaOcg0zlZ7sW6ZJIZKKZgjkYEl/X+N54nyFPtdNlGG3K1wngJZ5voIhZH2imOWv1CzQxOW1mOLHuNtqZ8OwB1ySZUZ0KjwTZObSFvLlKdOCnHHYYHxeFZh6vuMhY8HgtZP9I/ipXogQSASaQm2goQvxvLM16NjN23X5ZwHC2VgDCtUm4g5HeK8E0szQOPH9cs67kHkSOjRF1VdjYg5v0MRZ08eANxKRd2KR9zB5BDc8GV3Gp/nNlnO5cwZM/8kpd3cD3CuV7Gl3+cKESErQGFAklY8ofrmtn4ipe5dsCLyzdHyhHdGdgD+zt1nH7DX6/HCNjeiE95rs68Bw5JLwpNKE/uekkSXCH66cLNqqUMv54zGpn7yG0YvUGpbPuKQuqS92L7roDODz+JbeDz4Tk+gZSEh28Og7uKgDROyF3MQgzTd4Hiuxtr8/BFgcwG8g==
  template:
    metadata:
      name: imdbgraph-secrets
      namespace: imdbgraph
