[tools]
node = "22"
pnpm = "10.25.0"
kubeseal = "0.33.1"
kubectl = "1.34.3"
flux2 = "2.7.5"
pulumi = "3.197.0"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:opencode-ai" = "latest"

[env]
_.path = ['{{config_root}}/node_modules/.bin']
