apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dota-visualizer

resources:
  - ../base

nameSuffix: ''
namePrefix: dota-visualizer-

commonLabels:
  app: dota-visualizer

images:
  - name: docker.io/aamini/app
    newName: docker.io/aamini/dota-visualizer
    newTag: latest

patches:
  - target:
      kind: Namespace
      name: app
    patch: |-
      - op: replace
        path: /metadata/name
        value: dota-visualizer
  - target:
      kind: HTTPRoute
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: "dota-visualizer.ariaamini.com"
