apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pc-tune-ups

resources:
  - ../base

nameSuffix: ''
namePrefix: pc-tune-ups-

commonLabels:
  app: pc-tune-ups

images:
  - name: docker.io/aamini/app
    newName: docker.io/aamini/pc-tune-ups
    newTag: latest

patches:
  - target:
      kind: Namespace
      name: app
    patch: |-
      - op: replace
        path: /metadata/name
        value: pc-tune-ups
  - target:
      kind: HTTPRoute
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: "pc-tune-ups.ariaamini.com"
