---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ariaamini-com-wildcard
  namespace: networking
spec:
  secretName: ariaamini-com-tls
  dnsNames:
    - '*.ariaamini.com'
    - ariaamini.com
  privateKey:
    rotationPolicy: Always
  issuerRef:
    name: letsencrypt
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: networking
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acme-issuer-account-key
    solvers:
      - dns01:
          azureDNS:
            subscriptionID: ${AZURE_SUBSCRIPTION_ID}
            resourceGroupName: ${AZURE_DNS_RESOURCE_GROUP}
            hostedZoneName: ariaamini.com
            environment: AzurePublicCloud
            managedIdentity:
              clientID: ${CERT_MANAGER_CLIENT_ID}
