apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert.yaml
  - gateway.yaml
configMapGenerator:
  - name: networking-config
    namespace: flux-system
    envs:
      - .env
    options:
      disableNameSuffixHash: true
