---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: portfolio-root-http
  namespace: portfolio
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: networking
      sectionName: web
  hostnames:
    - ariaamini.com
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: portfolio-root-https
  namespace: portfolio
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: networking
      sectionName: websecure-root
  hostnames:
    - ariaamini.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: portfolio-app-service
          port: 80
