apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: portfolio

resources:
  - namespace.yaml
  - ../../../packages/infra/manifests/apps/base
  - httproute-root.yaml
  - sealed-secret.yaml

nameSuffix: ''
namePrefix: portfolio-

commonLabels:
  app: portfolio

images:
  - name: docker.io/aamini/app
    newName: docker.io/aamini/portfolio
    newTag: latest # {"$imagepolicy": "flux-system:portfolio:tag"}

patches:
  - target:
      kind: HTTPRoute
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: "portfolio.ariaamini.com"
  - target:
      kind: Deployment
      name: app-deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value:
          - secretRef:
              name: portfolio-secrets
