---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: imdbgraph-secrets
  namespace: imdbgraph
spec:
  encryptedData:
    DATABASE_PASSWORD: AgBYh7Ci0+flfKzrPzCgnP9T0SuOUQcFUIyf7xJH/1Du0QP14j6MoIX5ghzIEdmPpdOWPBdAME3TKBUfX+jWFxWF4VDJuLm3vDHOAIPp/cNmrn0C3WMz6TLEqEup821WK24P497l9I5VyDPtNMh6Le1QDZ7XD02J4ovWGDIYKB5PdVzN6qYEBr1fNFQFF9DjeEv8EXnv3bzkvgwnq6vspX5JCcv8OXZKv49+hgexO9+r/UVPzh0dfyKC/WEigTS7O3dVJsuoXuoyRgymA7qQ4+cI+zwEGoM4Sm3wdQY4pG7ba5tq8ms6l1n/5S2o+loKAGyOOa1cJQgaJhCwerO4KDfijQyjURy+kSk5RM1vID+Kvdicicojpbf3MOgEElw/5JWt9Rica+iOSIofNsBaxD/rxahQ0ypGXMnerZ77i/0bdMfZT0kToACSgS6m3kV9yYj877yfHbDPkn8zQBIMofbBuzYLFh9x+JbgY//kqRNRGK/xvR8gtfHtWlsntbOQqNRRZC2hU2HKaM68tNtpOy8oyHEqdsKITTaHeDf+i6NfL06dxUOtNo5CE0OfilkXtpVMhXpcER//d/vPY9fcNie/uu9Ktsux9hrH8BJvEjQTgOoCMw63WZTYsFQOKDA5/cDxS6K1oJMaEEMLZccBl9k/dLVHYsujZ+HhpuT4TMs7ehPeVPVEk6NykHW8YY4GV9Y5wGLUT1jCMmCKcJTxLoOB5az6Dbh09flAnpC5GoZZRQ==
  template:
    metadata:
      name: imdbgraph-secrets
      namespace: imdbgraph
