apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

nameSuffix: ''
namePrefix: portfolio-

commonLabels:
  app: portfolio

images:
  - name: docker.io/aamini/app
    newName: docker.io/aamini/portfolio
    newTag: latest

patches:
  - target:
      kind: HTTPRoute
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: "portfolio.ariaamini.com"
