apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: portfolio

resources:
  - ../base

nameSuffix: ""
namePrefix: portfolio-

commonLabels:
  app: portfolio

images:
  - name: ghcr.io/aamini-stack/app
    newName: ghcr.io/aamini-stack/portfolio
    newTag: main

patches:
  - target:
      kind: HTTPRoute
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: "ariaamini.dev"
