# App sources (Add 1 for each new app)
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: imdbgraph
  namespace: flux-system
spec:
  path: ./packages/infra/manifests/apps/imdbgraph
  dependsOn:
    - name: system
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 10m0s
  retryInterval: 1m0s
  timeout: 5m0s
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pc-tune-ups
  namespace: flux-system
spec:
  path: ./packages/infra/manifests/apps/pc-tune-ups
  dependsOn:
    - name: system
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 10m0s
  retryInterval: 1m0s
  timeout: 5m0s
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: portfolio
  namespace: flux-system
spec:
  path: ./packages/infra/manifests/apps/portfolio
  dependsOn:
    - name: system
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 10m0s
  retryInterval: 1m0s
  timeout: 5m0s
  prune: true


# System components
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system
  namespace: flux-system
spec:
  path: ./packages/infra/manifests/system
  dependsOn:
    - name: helm
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 1h0m0s
  retryInterval: 1m0s
  timeout: 5m0s
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helm
  namespace: flux-system
spec:
  path: ./packages/infra/manifests/packages
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 1h0m0s
  retryInterval: 1m0s
  timeout: 5m0s
  prune: true
