apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dota-visualizer

resources:
  - namespace.yaml
  - ../../../packages/infra/manifests/apps/base

nameSuffix: ''
namePrefix: dota-visualizer-

commonLabels:
  app: dota-visualizer

images:
  - name: docker.io/aamini/app
    newName: docker.io/aamini/dota-visualizer
    newTag: latest # {"$imagepolicy": "flux-system:dota-visualizer:tag"}

patches:
  - target:
      kind: HTTPRoute
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: "dota-visualizer.ariaamini.com"
